name: ItemPools
version: '${version}'
main: org.lushplugins.itempools.ItemPools
api-version: '1.20'
softdepend:
  - FancyHolograms
  - PlaceholderAPI
commands:
  itempools:
    usage: /itempools
    description: ItemPools main command